module: SwiftKueryORM
author: IBM & Kitura Project Authors
github_url: https://github.com/Kitura/Swift-Kuery-ORM

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false
