module: SwiftKueryORM
author: IBM
github_url: https://github.com/Kitura/Swift-Kuery-ORM

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftKueryORM.xcodeproj, -target, SwiftKueryORM, LIBRARY_SEARCH_PATHS=.build/debug]
